blueprint:
  name: RD1-Pro simple toggle + dim (zigbee2mqtt)
  description: Simple control: single press = toggle light, rotate = adjust brightness
  domain: automation

  input:
    remote_device:
      name: RD1-Pro Remote Device
      selector:
        device:
          filter:
            model_id:
              - C-ZB-RD1P-REM
              - C-ZB-RD1P-DPM
    light_target:
      name: Light to control
      selector:
        entity:
          domain: light
    brightness_step_pct:
      name: Brightness Step Percentage
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
      default: 5
    negative_brightness:
      name: Negative Brightness Step
      selector:
        number:
          min: -100
          max: -1
          unit_of_measurement: "%"
      default: -5

  mode: single

  triggers:
    - platform: device
      device_id: !input remote_device
      domain: mqtt
      type: action
      subtype: pressed
      id: pressed
    - platform: device
      device_id: !input remote_device
      domain: mqtt
      type: action
      subtype: started_rotating_right
      id: started_rotating_right
    - platform: device
      device_id: !input remote_device
      domain: mqtt
      type: action
      subtype: started_rotating_left
      id: started_rotating_left

  action:
    - choose:
        # Single press = toggle
        - conditions:
            - condition: trigger_id
              id: pressed
          sequence:
            - service: light.toggle
              target:
                entity_id: !input light_target

        # Rotate right = brighten
        - conditions:
            - condition: trigger_id
              id: started_rotating_right
          sequence:
            - service: light.turn_on
              target:
                entity_id: !input light_target
              data:
                brightness_step_pct: !input brightness_step_pct

        # Rotate left = dim
        - conditions:
            - condition: trigger_id
              id: started_rotating_left
          sequence:
            - service: light.turn_on
              target:
                entity_id: !input light_target
              data:
                brightness_step_pct: !input negative_brightness
