blueprint:
  name: RD1-Pro Smart Bulb Brightness & On/Off with Smooth Transition (Zigbee2MQTT)
  description: Control brightness and on/off only with Candeo RD1-Pro rotary dimmer, with smooth fading
  domain: automation
  input:
    remote_device:
      name: RD1-Pro Remote Device
      description: The RD1-Pro in Remote Mode
      selector:
        device:
          filter:
            - model_id: C-ZB-RD1P-REM
            - model_id: C-ZB-RD1P-DPM
    target_lights:
      name: Target Lights
      description: Lights or light groups to control
      selector:
        target:
          entity:
            domain: light
    brightness_step:
      name: Brightness Step (%)
      description: Brightness change per rotation step
      default: 3
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
    transition_time:
      name: Transition Time (seconds)
      description: Fade time for brightness changes
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

triggers:
  # Single press = toggle
  - device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: pressed
    id: toggle_lights

  # Rotation right = increase brightness
  - device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: started_rotating_right
    id: rotate_right
  - device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: rotating_right
    id: rotate_right

  # Rotation left = decrease brightness
  - device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: started_rotating_left
    id: rotate_left
  - device_id: !input remote_device
    domain: mqtt
    type: action
    subtype: rotating_left
    id: rotate_left

action:
  - choose:
      # Toggle lights
      - conditions:
          - condition: trigger
            id: toggle_lights
        sequence:
          - service: light.toggle
            target: "{{ target_lights }}"

      # Rotate right = increase brightness
      - conditions:
          - condition: trigger
            id: rotate_right
        sequence:
          - service: light.turn_on
            target: "{{ target_lights }}"
            data:
              brightness_step_pct: "{{ brightness_step }}"
              transition: !input transition_time

      # Rotate left = decrease brightness
      - conditions:
          - condition: trigger
            id: rotate_left
        sequence:
          - service: light.turn_on
            target: "{{ target_lights }}"
            data:
              brightness_step_pct: -{{ brightness_step }}
              transition: !input transition_time
